import type { ConfigUiHints } from "../types.ts";

export type JsonSchema = {
  type?: string | string[];
  title?: string;
  description?: string;
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema | JsonSchema[];
  additionalProperties?: JsonSchema | boolean;
  enum?: unknown[];
  const?: unknown;
  default?: unknown;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  nullable?: boolean;
};

export function schemaType(schema: JsonSchema): string | undefined {
  if (!schema) {
    return undefined;
  }
  if (Array.isArray(schema.type)) {
    const filtered = schema.type.filter((t) => t !== "null");
    return filtered[0] ?? schema.type[0];
  }
  return schema.type;
}

export function defaultValue(schema?: JsonSchema): unknown {
  if (!schema) {
    return "";
  }
  if (schema.default !== undefined) {
    return schema.default;
  }
  const type = schemaType(schema);
  switch (type) {
    case "object":
      return {};
    case "array":
      return [];
    case "boolean":
      return false;
    case "number":
    case "integer":
      return 0;
    case "string":
      return "";
    default:
      return "";
  }
}

export function pathKey(path: Array<string | number>): string {
  return path.filter((segment) => typeof segment === "string").join(".");
}

export function hintForPath(path: Array<string | number>, hints: ConfigUiHints) {
  const key = pathKey(path);
  const direct = hints[key];
  if (direct) {
    return direct;
  }
  const segments = key.split(".");
  for (const [hintKey, hint] of Object.entries(hints)) {
    if (!hintKey.includes("*")) {
      continue;
    }
    const hintSegments = hintKey.split(".");
    if (hintSegments.length !== segments.length) {
      continue;
    }
    let match = true;
    for (let i = 0; i < segments.length; i += 1) {
      if (hintSegments[i] !== "*" && hintSegments[i] !== segments[i]) {
        match = false;
        break;
      }
    }
    if (match) {
      return hint;
    }
  }
  return undefined;
}

// 常用配置字段的中文翻译
const FIELD_TRANSLATIONS: Record<string, string> = {
  // 通用字段
  enabled: "启用",
  disabled: "禁用",
  name: "名称",
  description: "描述",
  type: "类型",
  value: "值",
  default: "默认值",
  options: "选项",
  settings: "设置",
  config: "配置",
  configuration: "配置",
  status: "状态",
  state: "状态",
  mode: "模式",
  level: "级别",
  priority: "优先级",
  order: "顺序",
  index: "索引",
  id: "ID",
  key: "键",
  label: "标签",
  title: "标题",
  text: "文本",
  message: "消息",
  content: "内容",
  data: "数据",
  info: "信息",
  details: "详情",
  summary: "摘要",
  result: "结果",
  output: "输出",
  input: "输入",
  source: "来源",
  target: "目标",
  destination: "目的地",
  path: "路径",
  url: "URL",
  uri: "URI",
  host: "主机",
  port: "端口",
  address: "地址",
  endpoint: "端点",
  server: "服务器",
  client: "客户端",
  connection: "连接",
  timeout: "超时",
  interval: "间隔",
  delay: "延迟",
  duration: "持续时间",
  timestamp: "时间戳",
  date: "日期",
  time: "时间",
  start: "开始",
  end: "结束",
  created: "创建时间",
  updated: "更新时间",
  modified: "修改时间",
  deleted: "删除时间",
  expires: "过期时间",
  version: "版本",
  format: "格式",
  encoding: "编码",
  language: "语言",
  locale: "区域设置",
  timezone: "时区",
  currency: "货币",
  country: "国家",
  region: "地区",
  city: "城市",
  zip: "邮编",
  phone: "电话",
  email: "邮箱",
  username: "用户名",
  password: "密码",
  token: "令牌",
  secret: "密钥",
  apiKey: "API 密钥",
  accessToken: "访问令牌",
  refreshToken: "刷新令牌",
  auth: "认证",
  authentication: "认证",
  authorization: "授权",
  permission: "权限",
  permissions: "权限",
  role: "角色",
  roles: "角色",
  user: "用户",
  users: "用户",
  group: "群组",
  groups: "群组",
  team: "团队",
  teams: "团队",
  organization: "组织",
  organizations: "组织",
  account: "账户",
  accounts: "账户",
  profile: "个人资料",
  avatar: "头像",
  image: "图片",
  photo: "照片",
  icon: "图标",
  logo: "标志",
  file: "文件",
  files: "文件",
  folder: "文件夹",
  directory: "目录",
  upload: "上传",
  download: "下载",
  import: "导入",
  export: "导出",
  backup: "备份",
  restore: "恢复",
  sync: "同步",
  cache: "缓存",
  storage: "存储",
  database: "数据库",
  table: "表",
  column: "列",
  row: "行",
  record: "记录",
  query: "查询",
  filter: "过滤器",
  sort: "排序",
  search: "搜索",
  find: "查找",
  replace: "替换",
  match: "匹配",
  pattern: "模式",
  regex: "正则表达式",
  template: "模板",
  layout: "布局",
  theme: "主题",
  style: "样式",
  color: "颜色",
  background: "背景",
  border: "边框",
  margin: "外边距",
  padding: "内边距",
  width: "宽度",
  height: "高度",
  size: "大小",
  scale: "缩放",
  zoom: "缩放",
  rotate: "旋转",
  flip: "翻转",
  align: "对齐",
  position: "位置",
  location: "位置",
  coordinates: "坐标",
  latitude: "纬度",
  longitude: "经度",
  altitude: "海拔",
  speed: "速度",
  velocity: "速度",
  acceleration: "加速度",
  direction: "方向",
  angle: "角度",
  distance: "距离",
  area: "面积",
  volume: "体积",
  weight: "重量",
  mass: "质量",
  density: "密度",
  temperature: "温度",
  pressure: "压力",
  humidity: "湿度",
  brightness: "亮度",
  contrast: "对比度",
  saturation: "饱和度",
  opacity: "不透明度",
  transparency: "透明度",
  visibility: "可见性",
  display: "显示",
  show: "显示",
  hide: "隐藏",
  visible: "可见",
  hidden: "隐藏",
  active: "活动",
  inactive: "非活动",
  online: "在线",
  offline: "离线",
  connected: "已连接",
  disconnected: "已断开",
  available: "可用",
  unavailable: "不可用",
  busy: "忙碌",
  idle: "空闲",
  pending: "待处理",
  processing: "处理中",
  completed: "已完成",
  failed: "失败",
  success: "成功",
  error: "错误",
  warning: "警告",
  notice: "通知",
  alert: "警报",
  notification: "通知",
  notifications: "通知",
  event: "事件",
  events: "事件",
  action: "动作",
  actions: "动作",
  trigger: "触发器",
  triggers: "触发器",
  hook: "钩子",
  hooks: "钩子",
  callback: "回调",
  handler: "处理器",
  listener: "监听器",
  observer: "观察者",
  subscriber: "订阅者",
  publisher: "发布者",
  producer: "生产者",
  consumer: "消费者",
  sender: "发送者",
  receiver: "接收者",
  request: "请求",
  response: "响应",
  header: "请求头",
  headers: "请求头",
  body: "请求体",
  payload: "负载",
  params: "参数",
  parameters: "参数",
  args: "参数",
  arguments: "参数",
  method: "方法",
  function: "函数",
  procedure: "过程",
  routine: "例程",
  task: "任务",
  tasks: "任务",
  job: "作业",
  jobs: "作业",
  process: "进程",
  thread: "线程",
  worker: "工作线程",
  queue: "队列",
  stack: "栈",
  buffer: "缓冲区",
  stream: "流",
  channel: "频道",
  channels: "频道",
  pipe: "管道",
  socket: "套接字",
  protocol: "协议",
  scheme: "方案",
  domain: "域名",
  subdomain: "子域名",
  namespace: "命名空间",
  scope: "作用域",
  context: "上下文",
  environment: "环境",
  platform: "平台",
  system: "系统",
  os: "操作系统",
  browser: "浏览器",
  device: "设备",
  devices: "设备",
  hardware: "硬件",
  software: "软件",
  firmware: "固件",
  driver: "驱动",
  plugin: "插件",
  plugins: "插件",
  extension: "扩展",
  extensions: "扩展",
  addon: "附加组件",
  addons: "附加组件",
  module: "模块",
  modules: "模块",
  package: "包",
  packages: "包",
  library: "库",
  libraries: "库",
  framework: "框架",
  sdk: "SDK",
  api: "API",
  rest: "REST",
  graphql: "GraphQL",
  grpc: "gRPC",
  websocket: "WebSocket",
  http: "HTTP",
  https: "HTTPS",
  ftp: "FTP",
  ssh: "SSH",
  ssl: "SSL",
  tls: "TLS",
  tcp: "TCP",
  udp: "UDP",
  ip: "IP",
  dns: "DNS",
  dhcp: "DHCP",
  vpn: "VPN",
  proxy: "代理",
  firewall: "防火墙",
  gateway: "网关",
  router: "路由器",
  switch: "交换机",
  hub: "集线器",
  bridge: "网桥",
  modem: "调制解调器",
  antenna: "天线",
  signal: "信号",
  frequency: "频率",
  bandwidth: "带宽",
  latency: "延迟",
  throughput: "吞吐量",
  capacity: "容量",
  limit: "限制",
  limits: "限制",
  quota: "配额",
  rate: "速率",
  count: "计数",
  total: "总计",
  sum: "总和",
  average: "平均",
  min: "最小",
  max: "最大",
  minimum: "最小值",
  maximum: "最大值",
  range: "范围",
  threshold: "阈值",
  percentage: "百分比",
  ratio: "比率",
  factor: "因子",
  multiplier: "乘数",
  divisor: "除数",
  remainder: "余数",
  modulo: "模",
  increment: "增量",
  decrement: "减量",
  step: "步长",
  offset: "偏移",
  gap: "间隙",
  spacing: "间距",
  indent: "缩进",
  wrap: "换行",
  truncate: "截断",
  ellipsis: "省略号",
  prefix: "前缀",
  suffix: "后缀",
  separator: "分隔符",
  delimiter: "定界符",
  quote: "引号",
  escape: "转义",
  encode: "编码",
  decode: "解码",
  encrypt: "加密",
  decrypt: "解密",
  hash: "哈希",
  sign: "签名",
  verify: "验证",
  validate: "校验",
  sanitize: "清理",
  normalize: "规范化",
  transform: "转换",
  convert: "转换",
  parse: "解析",
  stringify: "字符串化",
  serialize: "序列化",
  deserialize: "反序列化",
  compress: "压缩",
  decompress: "解压",
  unzip: "解压",
  archive: "归档",
  extract: "提取",
  merge: "合并",
  split: "拆分",
  join: "连接",
  concat: "连接",
  append: "追加",
  prepend: "前置",
  insert: "插入",
  remove: "移除",
  delete: "删除",
  clear: "清除",
  reset: "重置",
  refresh: "刷新",
  reload: "重新加载",
  restart: "重启",
  stop: "停止",
  pause: "暂停",
  resume: "恢复",
  cancel: "取消",
  abort: "中止",
  retry: "重试",
  skip: "跳过",
  ignore: "忽略",
  accept: "接受",
  reject: "拒绝",
  approve: "批准",
  deny: "拒绝",
  allow: "允许",
  block: "阻止",
  ban: "禁止",
  mute: "静音",
  unmute: "取消静音",
  lock: "锁定",
  unlock: "解锁",
  open: "打开",
  close: "关闭",
  expand: "展开",
  collapse: "折叠",
  maximize: "最大化",
  minimize: "最小化",
  fullscreen: "全屏",
  windowed: "窗口化",
  // 特定于此项目的字段
  web: "Web 服务",
  nodehost: "节点主机",
  nodeHost: "节点主机",
  media: "媒体",
  approvals: "审批",
  approval: "审批",
  lastRunAt: "上次运行时间",
  updateChannel: "更新渠道",
  controlUi: "控制界面",
  allowlist: "白名单",
  blocklist: "黑名单",
  whitelist: "白名单",
  blacklist: "黑名单",
  routing: "路由",
  pairing: "配对",
  presence: "在线状态",
  memory: "记忆",
  mcp: "MCP",
  diagnostics: "诊断",
  telemetry: "遥测",
  security: "安全",
  network: "网络",
  canvasHost: "画布主机",
  talk: "语音",
  discovery: "发现",
  broadcast: "广播",
  audio: "音频",
  session: "会话",
  sessions: "会话",
  cron: "定时任务",
  skills: "技能",
  skill: "技能",
  tools: "工具",
  tool: "工具",
  commands: "命令",
  command: "命令",
  messages: "消息",
  agents: "代理",
  agent: "代理",
  agentId: "代理 ID",
  models: "模型",
  model: "模型",
  bindings: "绑定",
  binding: "绑定",
  logging: "日志",
  logs: "日志",
  log: "日志",
  wizard: "向导",
  meta: "元数据",
  env: "环境变量",
  update: "更新",
  ui: "界面",
  experimental: "实验性",
  advanced: "高级",
  developer: "开发者",
  debug: "调试",
  performance: "性能",
  thinking: "思考",
  thinkingLevel: "思考级别",
  verbose: "详细",
  verboseLevel: "详细级别",
  reasoning: "推理",
  reasoningLevel: "推理级别",
  provider: "提供商",
  providers: "提供商",
  apiKeys: "API 密钥",
  credentials: "凭证",
  tokens: "令牌",
  secrets: "密钥",
  certificates: "证书",
  encryption: "加密",
  hashing: "哈希",
  signing: "签名",
  verification: "验证",
  validation: "校验",
  sanitization: "清理",
  formatting: "格式化",
  parsing: "解析",
  serialization: "序列化",
  deserialization: "反序列化",
  compression: "压缩",
  decompression: "解压",
  sessionKey: "会话密钥",
  sessionTarget: "会话目标",
  wakeMode: "唤醒模式",
  payloadKind: "负载类型",
  payloadText: "负载文本",
  scheduleKind: "调度方式",
  scheduleAt: "调度时间",
  everyAmount: "间隔数量",
  everyUnit: "间隔单位",
  cronExpr: "Cron 表达式",
  cronTz: "Cron 时区",
  deliver: "投递",
  postToMainPrefix: "发送到主会话前缀",
  timeoutSeconds: "超时秒数",
  lastStartAt: "上次启动时间",
  lastProbeAt: "上次探测时间",
  lastError: "上次错误",
  lastInboundAt: "上次入站时间",
  configured: "已配置",
  running: "运行中",
  bind: "绑定",
  bindAddress: "绑定地址",
  listenPort: "监听端口",
  maxConnections: "最大连接数",
  maxRequestSize: "最大请求大小",
  maxResponseSize: "最大响应大小",
  maxBodySize: "最大请求体大小",
  maxHeaderSize: "最大请求头大小",
  maxUploadSize: "最大上传大小",
  maxDownloadSize: "最大下载大小",
  maxFileSize: "最大文件大小",
  maxFiles: "最大文件数",
  maxRetries: "最大重试次数",
  retryDelay: "重试延迟",
  retryInterval: "重试间隔",
  connectTimeout: "连接超时",
  readTimeout: "读取超时",
  writeTimeout: "写入超时",
  idleTimeout: "空闲超时",
  keepAlive: "保持连接",
  keepAliveTimeout: "保持连接超时",
  heartbeat: "心跳",
  heartbeatInterval: "心跳间隔",
  pingInterval: "Ping 间隔",
  pingTimeout: "Ping 超时",
  reconnect: "重连",
  reconnectInterval: "重连间隔",
  reconnectDelay: "重连延迟",
  autoReconnect: "自动重连",
  autoStart: "自动启动",
  autoStop: "自动停止",
  autoSave: "自动保存",
  autoLoad: "自动加载",
  autoUpdate: "自动更新",
  autoRefresh: "自动刷新",
  autoSync: "自动同步",
  autoBackup: "自动备份",
  autoRestore: "自动恢复",
  autoClean: "自动清理",
  autoPurge: "自动清除",
  autoDelete: "自动删除",
  autoArchive: "自动归档",
  autoCompress: "自动压缩",
  autoDecompress: "自动解压",
  autoEncrypt: "自动加密",
  autoDecrypt: "自动解密",
  execApprovals: "执行审批",
  allowInsecureAuth: "允许不安全认证",
  allowAnonymous: "允许匿名",
  requireAuth: "需要认证",
  requireHttps: "需要 HTTPS",
  requireSsl: "需要 SSL",
  requireTls: "需要 TLS",
  enableCors: "启用 CORS",
  enableGzip: "启用 Gzip",
  enableCache: "启用缓存",
  enableLogging: "启用日志",
  enableDebug: "启用调试",
  enableMetrics: "启用指标",
  enableTracing: "启用追踪",
  enableProfiling: "启用性能分析",
  enableHealthCheck: "启用健康检查",
  enableRateLimit: "启用速率限制",
  enableThrottle: "启用节流",
  enableRetry: "启用重试",
  enableFallback: "启用回退",
  enableCircuitBreaker: "启用熔断器",
  enableLoadBalancer: "启用负载均衡",
  enableServiceDiscovery: "启用服务发现",
  enableAutoScaling: "启用自动扩缩",
  enableAutoHealing: "启用自动修复",
  enableAutoRecovery: "启用自动恢复",
  enableAutoFailover: "启用自动故障转移",
  enableAutoBackup: "启用自动备份",
  enableAutoRestore: "启用自动恢复",
  enableAutoCleanup: "启用自动清理",
  enableAutoPurge: "启用自动清除",
  enableAutoArchive: "启用自动归档",
  enableAutoCompress: "启用自动压缩",
  enableAutoEncrypt: "启用自动加密",
  stable: "稳定版",
  beta: "测试版",
  dev: "开发版",
  latest: "最新版",
  current: "当前版本",
  previous: "上一版本",
  next: "下一版本",
  release: "发布版",
  prerelease: "预发布版",
  snapshot: "快照版",
  nightly: "每夜版",
  canary: "金丝雀版",
  alpha: "Alpha 版",
  rc: "RC 版",
  ga: "GA 版",
  lts: "LTS 版",
  sts: "STS 版",
  eol: "EOL 版",
  deprecated: "已弃用",
  obsolete: "已过时",
  legacy: "旧版",
  modern: "现代版",
  classic: "经典版",
  standard: "标准版",
  professional: "专业版",
  enterprise: "企业版",
  community: "社区版",
  personal: "个人版",
  free: "免费版",
  paid: "付费版",
  trial: "试用版",
  demo: "演示版",
  sample: "示例版",
  test: "测试版",
  prod: "生产版",
  production: "生产环境",
  staging: "预发布环境",
  development: "开发环境",
  testing: "测试环境",
  local: "本地",
  remote: "远程",
  cloud: "云",
  onpremise: "本地部署",
  hybrid: "混合部署",
  multicloud: "多云部署",
  singlecloud: "单云部署",
  privatecloud: "私有云",
  publiccloud: "公有云",
  communitycloud: "社区云",
  // camelCase 复合词翻译
  humanDelay: "人类延迟",
  includeReasoning: "包含推理",
  idleMs: "空闲毫秒",
  breakPreference: "断行偏好",
  maxChars: "最大字符数",
  minChars: "最小字符数",
  headChars: "头部字符数",
  tailChars: "尾部字符数",
  maxBytes: "最大字节数",
  maxLines: "最大行数",
  maxTokens: "最大令牌数",
  maxResults: "最大结果数",
  maxLinks: "最大链接数",
  maxRedirects: "最大重定向数",
  maxConcurrent: "最大并发数",
  maxSize: "最大大小",
  maxAge: "最大年龄",
  maxWidth: "最大宽度",
  maxHeight: "最大高度",
  minMs: "最小毫秒",
  maxMs: "最大毫秒",
  minDelayMs: "最小延迟毫秒",
  maxDelayMs: "最大延迟毫秒",
  timeoutMs: "超时毫秒",
  intervalMs: "间隔毫秒",
  debounceMs: "防抖毫秒",
  pollIntervalMs: "轮询间隔毫秒",
  flushIntervalMs: "刷新间隔毫秒",
  watchDebounceMs: "监视防抖毫秒",
  retryAttempts: "重试次数",
  retryJitter: "重试抖动",
  jitter: "抖动",
  sampleRate: "采样率",
  softTrimRatio: "软裁剪比例",
  hardClearRatio: "硬清除比例",
  vectorWeight: "向量权重",
  textWeight: "文本权重",
  candidateMultiplier: "候选乘数",
  maxHistoryShare: "最大历史占比",
  reserveTokensFloor: "保留令牌下限",
  softThresholdTokens: "软阈值令牌数",
  deltaBytes: "增量字节数",
  deltaMessages: "增量消息数",
  contextTokens: "上下文令牌数",
  totalTokens: "总令牌数",
  inputTokens: "输入令牌数",
  outputTokens: "输出令牌数",
  cacheRead: "缓存读取",
  cacheWrite: "缓存写入",
  cacheTtlMinutes: "缓存 TTL 分钟",
  maxEntries: "最大条目数",
  maxAgeMs: "最大年龄毫秒",
  onlyMainContent: "仅主要内容",
  autoSelectFamily: "自动选择协议族",
  dangerouslyDisableDeviceAuth: "危险禁用设备认证",
  requireMention: "需要提及",
  allowBots: "允许机器人",
  inheritParent: "继承父级",
  historyScope: "历史范围",
  dmPolicy: "私信策略",
  selfChatMode: "自聊模式",
  streamMode: "流模式",
  chatmode: "聊天模式",
  oncharPrefixes: "触发前缀",
  inlineButtons: "内联按钮",
  guildMembers: "服务器成员",
  pluralkitEnabled: "PluralKit 启用",
  pluralkitToken: "PluralKit 令牌",
  maxLinesPerMessage: "每条消息最大行数",
  botToken: "机器人令牌",
  appToken: "应用令牌",
  userToken: "用户令牌",
  userTokenReadOnly: "用户令牌只读",
  baseUrl: "基础 URL",
  serviceName: "服务名称",
  filePath: "文件路径",
  modelPath: "模型路径",
  installPath: "安装路径",
  sourcePath: "源路径",
  extensionPath: "扩展路径",
  basePath: "基础路径",
  cliPath: "CLI 路径",
  repoRoot: "仓库根目录",
  extraPaths: "额外路径",
  loadPaths: "加载路径",
  pathPrepend: "PATH 前置",
  safeBins: "安全二进制",
  allowCommands: "允许命令",
  denyCommands: "拒绝命令",
  nativeCommands: "原生命令",
  nativeSkills: "原生技能",
  customCommands: "自定义命令",
  textCommands: "文本命令",
  bashCommand: "Bash 命令",
  bashForegroundMs: "Bash 前台毫秒",
  useAccessGroups: "使用访问组",
  allowCrossContextSend: "允许跨上下文发送",
  allowWithinProvider: "允许同提供商内",
  allowAcrossProviders: "允许跨提供商",
  markerEnabled: "标记启用",
  markerPrefix: "标记前缀",
  markerSuffix: "标记后缀",
  broadcastEnabled: "广播启用",
  searchEnabled: "搜索启用",
  fetchEnabled: "抓取启用",
  evaluateEnabled: "执行启用",
  applyPatchEnabled: "应用补丁启用",
  allowModels: "允许模型",
  notifyOnExit: "退出时通知",
  approvalRunningNoticeMs: "审批运行通知毫秒",
  execHost: "执行主机",
  execSecurity: "执行安全",
  execAsk: "执行询问",
  execNode: "执行节点",
  imageEnabled: "图片启用",
  audioEnabled: "音频启用",
  videoEnabled: "视频启用",
  linksEnabled: "链接启用",
  mediaMaxMb: "媒体最大 MB",
  attachments: "附件",
  concurrency: "并发数",
  includeMessages: "包含消息",
  includePrompt: "包含提示词",
  includeSystem: "包含系统",
  sessionMemory: "会话记忆",
  memorySearch: "记忆搜索",
  memoryFlush: "记忆刷新",
  contextPruning: "上下文裁剪",
  softTrim: "软裁剪",
  hardClear: "硬清除",
  compaction: "压缩",
  keepLastAssistants: "保留最后助手数",
  minPrunableToolChars: "最小可裁剪工具字符",
  onSessionStart: "会话开始时",
  onSearch: "搜索时",
  watchEnabled: "监视启用",
  hybridEnabled: "混合启用",
  vectorEnabled: "向量启用",
  cacheEnabled: "缓存启用",
  batchEnabled: "批处理启用",
  batchWait: "批处理等待",
  batchConcurrency: "批处理并发",
  timeoutMinutes: "超时分钟",
  chunkTokens: "分块令牌",
  overlapTokens: "重叠令牌",
  minScore: "最小分数",
  fallbackProvider: "回退提供商",
  primaryModel: "主模型",
  fallbackModels: "回退模型",
  imageModel: "图像模型",
  thinkingDefault: "默认思考",
  verboseDefault: "默认详细",
  elevatedDefault: "默认提权",
  blockStreamingDefault: "默认块流",
  blockStreamingBreak: "块流断点",
  blockStreamingChunk: "块流分块",
  blockStreamingCoalesce: "块流合并",
  typingMode: "输入模式",
  typingIntervalSeconds: "输入间隔秒",
  heartbeatTarget: "心跳目标",
  heartbeatIntervalMs: "心跳间隔毫秒",
  archiveAfterMinutes: "归档分钟后",
  subagentModel: "子代理模型",
  subagentTools: "子代理工具",
  envelopeTimezone: "信封时区",
  envelopeTimestamp: "信封时间戳",
  envelopeElapsed: "信封已用时间",
  bootstrapMaxChars: "引导最大字符",
  ackReaction: "确认反应",
  ackReactionScope: "确认反应范围",
  inboundDebounceMs: "入站防抖毫秒",
  remoteUrl: "远程 URL",
  sshTarget: "SSH 目标",
  sshIdentity: "SSH 身份",
  tlsFingerprint: "TLS 指纹",
  gatewayToken: "网关令牌",
  gatewayPassword: "网关密码",
  controlUiBasePath: "控制界面基础路径",
  reloadMode: "重载模式",
  reloadDebounceMs: "重载防抖毫秒",
  browserMode: "浏览器模式",
  browserNode: "浏览器节点",
  browserProxyEnabled: "浏览器代理启用",
  allowProfiles: "允许配置文件",
  otelEnabled: "OpenTelemetry 启用",
  otelEndpoint: "OpenTelemetry 端点",
  otelProtocol: "OpenTelemetry 协议",
  otelHeaders: "OpenTelemetry 请求头",
  otelTraces: "OpenTelemetry 追踪",
  otelMetrics: "OpenTelemetry 指标",
  otelLogs: "OpenTelemetry 日志",
  cacheTraceEnabled: "缓存追踪启用",
  cacheTraceFilePath: "缓存追踪文件路径",
  pluginsEnabled: "插件启用",
  pluginAllow: "插件白名单",
  pluginDeny: "插件黑名单",
  pluginSlots: "插件槽位",
  memoryPlugin: "记忆插件",
  mdnsMode: "mDNS 模式",
  lastTouchedVersion: "最后修改版本",
  lastTouchedAt: "最后修改时间",
  lastRunVersion: "上次运行版本",
  lastRunCommand: "上次运行命令",
  lastRunMode: "上次运行模式",
  lastRunCommit: "上次运行提交",
  lastStatus: "上次状态",
  nextRunAtMs: "下次运行时间",
  lastRunAtMs: "上次运行时间",
  installedAt: "安装时间",
  checkOnStart: "启动时检查",
  billingBackoffHours: "计费退避小时",
  billingBackoffHoursByProvider: "按提供商计费退避",
  billingMaxHours: "计费最大小时",
  failureWindowHours: "故障窗口小时",
  configWrites: "配置写入",
  seamColor: "强调色",
  assistantName: "助手名称",
  assistantAvatar: "助手头像",
  snapshotMode: "快照模式",
  remoteCdpTimeoutMs: "远程 CDP 超时毫秒",
  remoteCdpHandshakeTimeoutMs: "远程 CDP 握手超时毫秒",
  dmScope: "私信范围",
  identityLinks: "身份链接",
  maxPingPongTurns: "最大乒乓轮次",
  talkApiKey: "语音 API 密钥",
  // 更多 camelCase 复合词翻译
  cacheTrace: "缓存追踪",
  resetOnExit: "退出时重置",
  autoGenerate: "自动生成",
  trustedProxies: "受信任代理",
  allowedOrigins: "允许的来源",
  allowedHosts: "允许的主机",
  allowFrom: "允许来源",
  denyFrom: "拒绝来源",
  alsoAllow: "额外允许",
  alsoDeny: "额外拒绝",
  byProvider: "按提供商",
  chatCompletions: "聊天补全",
  publicUrl: "公开 URL",
  privateUrl: "私有 URL",
  webhookUrl: "Webhook URL",
  callbackUrl: "回调 URL",
  redirectUrl: "重定向 URL",
  proxyUrl: "代理 URL",
  gatewayUrl: "网关 URL",
  serverUrl: "服务器 URL",
  clientId: "客户端 ID",
  clientSecret: "客户端密钥",
  appId: "应用 ID",
  appSecret: "应用密钥",
  corpId: "企业 ID",
  corpSecret: "企业密钥",
  botId: "机器人 ID",
  userId: "用户 ID",
  groupId: "群组 ID",
  channelId: "频道 ID",
  threadId: "线程 ID",
  messageId: "消息 ID",
  sessionId: "会话 ID",
  requestId: "请求 ID",
  responseId: "响应 ID",
  eventId: "事件 ID",
  taskId: "任务 ID",
  jobId: "作业 ID",
  workerId: "工作线程 ID",
  nodeId: "节点 ID",
  peerId: "对等 ID",
  deviceId: "设备 ID",
  accountId: "账户 ID",
  profileId: "配置文件 ID",
  templateId: "模板 ID",
  schemaId: "架构 ID",
  pluginId: "插件 ID",
  extensionId: "扩展 ID",
  moduleId: "模块 ID",
  packageId: "包 ID",
  versionId: "版本 ID",
  releaseId: "发布 ID",
  buildId: "构建 ID",
  commitId: "提交 ID",
  branchId: "分支 ID",
  tagId: "标签 ID",
  issueId: "问题 ID",
  pullRequestId: "拉取请求 ID",
  mergeRequestId: "合并请求 ID",
  reviewId: "审查 ID",
  commentId: "评论 ID",
  reactionId: "反应 ID",
  attachmentId: "附件 ID",
  fileId: "文件 ID",
  folderId: "文件夹 ID",
  directoryId: "目录 ID",
  pathId: "路径 ID",
  urlId: "URL ID",
  linkId: "链接 ID",
  referenceId: "引用 ID",
  sourceId: "来源 ID",
  targetId: "目标 ID",
  destinationId: "目的地 ID",
  originId: "来源 ID",
  parentId: "父级 ID",
  childId: "子级 ID",
  rootId: "根 ID",
  headId: "头 ID",
  tailId: "尾 ID",
  startId: "开始 ID",
  endId: "结束 ID",
  firstId: "第一个 ID",
  lastId: "最后一个 ID",
  nextId: "下一个 ID",
  prevId: "上一个 ID",
  currentId: "当前 ID",
  defaultId: "默认 ID",
  primaryId: "主 ID",
  secondaryId: "次 ID",
  fallbackId: "回退 ID",
  backupId: "备份 ID",
  mainId: "主 ID",
  altId: "备用 ID",
  tempId: "临时 ID",
  cacheId: "缓存 ID",
  storeId: "存储 ID",
  queueId: "队列 ID",
  stackId: "栈 ID",
  bufferPath: "缓冲区路径",
  streamPath: "流路径",
  channelPath: "频道路径",
  pipePath: "管道路径",
  socketPath: "套接字路径",
  protocolVersion: "协议版本",
  schemaVersion: "架构版本",
  apiVersion: "API 版本",
  appVersion: "应用版本",
  clientVersion: "客户端版本",
  serverVersion: "服务器版本",
  nodeVersion: "节点版本",
  runtimeVersion: "运行时版本",
  engineVersion: "引擎版本",
  frameworkVersion: "框架版本",
  libraryVersion: "库版本",
  packageVersion: "包版本",
  moduleVersion: "模块版本",
  pluginVersion: "插件版本",
  extensionVersion: "扩展版本",
  driverVersion: "驱动版本",
  firmwareVersion: "固件版本",
  hardwareVersion: "硬件版本",
  softwareVersion: "软件版本",
  osVersion: "操作系统版本",
  kernelVersion: "内核版本",
  buildVersion: "构建版本",
  releaseVersion: "发布版本",
  majorVersion: "主版本",
  minorVersion: "次版本",
  patchVersion: "补丁版本",
  preReleaseVersion: "预发布版本",
  snapshotVersion: "快照版本",
  nightlyVersion: "每夜版本",
  canaryVersion: "金丝雀版本",
  stableVersion: "稳定版本",
  betaVersion: "测试版本",
  alphaVersion: "Alpha 版本",
  devVersion: "开发版本",
  latestVersion: "最新版本",
  currentVersion: "当前版本",
  previousVersion: "上一版本",
  nextVersion: "下一版本",
  targetVersion: "目标版本",
  minimumVersion: "最低版本",
  maximumVersion: "最高版本",
  requiredVersion: "必需版本",
  recommendedVersion: "推荐版本",
  supportedVersion: "支持版本",
  deprecatedVersion: "已弃用版本",
  obsoleteVersion: "已过时版本",
  legacyVersion: "旧版本",
  // Tailscale 和网络相关
  allowTailscale: "允许 Tailscale",
  tailscale: "Tailscale",
  endpoints: "端点",
  nodes: "节点",
  browserProxy: "浏览器代理",
  // 消息和确认相关
  ackMaxChars: "确认最大字符数",
  ack: "确认",
  // 时间和调度相关
  activeHours: "活动时间",
  intervalMinutes: "间隔分钟",
  intervalSeconds: "间隔秒",
  // 控制和启动相关
  allowHostControl: "允许主机控制",
  autoStartTimeoutMs: "自动启动超时毫秒",
  autoStartTimeout: "自动启动超时",
  // CDP 和浏览器相关
  cdpPort: "CDP 端口",
  cdpUrl: "CDP URL",
  cdpTimeout: "CDP 超时",
  // 容器和安全相关
  containerPrefix: "容器前缀",
  apparmorProfile: "AppArmor 配置文件",
  apparmor: "AppArmor",
  seccompProfile: "Seccomp 配置文件",
  // 浏览器自动化
  headless: "无头模式",
  headlessMode: "无头模式",
  browserPath: "浏览器路径",
  browserArgs: "浏览器参数",
  userDataDir: "用户数据目录",
  downloadPath: "下载路径",
  screenshotPath: "截图路径",
  // 代理相关
  proxyEnabled: "代理启用",
  proxyHost: "代理主机",
  proxyPort: "代理端口",
  proxyUsername: "代理用户名",
  proxyPassword: "代理密码",
  proxyBypass: "代理绕过",
  // 限制和配额
  maxMessages: "最大消息数",
  maxTurns: "最大轮次",
  maxLength: "最大长度",
  maxDepth: "最大深度",
  maxCount: "最大数量",
  maxItems: "最大项目数",
  maxPages: "最大页数",
  // 功能开关
  allowImages: "允许图片",
  allowFiles: "允许文件",
  allowLinks: "允许链接",
  allowCode: "允许代码",
  allowMarkdown: "允许 Markdown",
  allowHtml: "允许 HTML",
  allowEmoji: "允许表情",
  allowMentions: "允许提及",
  allowReactions: "允许反应",
  allowThreads: "允许线程",
  allowReplies: "允许回复",
  allowForwards: "允许转发",
  allowEdits: "允许编辑",
  allowDeletes: "允许删除",
  // 会话相关
  sessionTimeout: "会话超时",
  sessionMaxAge: "会话最大时长",
  sessionStore: "会话存储",
  // 日志相关
  logLevel: "日志级别",
  logFormat: "日志格式",
  logPath: "日志路径",
  logFile: "日志文件",
  logMaxSize: "日志最大大小",
  logMaxFiles: "日志最大文件数",
  logRotate: "日志轮转",
  // 缓存相关
  cacheTtl: "缓存 TTL",
  cacheMaxSize: "缓存最大大小",
  cacheMaxAge: "缓存最大时长",
  cachePath: "缓存路径",
  // 重试相关
  retryEnabled: "重试启用",
  retryDelayMs: "重试延迟毫秒",
  retryMaxDelay: "重试最大延迟",
  retryBackoff: "重试退避",
  // 速率限制
  rateLimit: "速率限制",
  rateLimitEnabled: "速率限制启用",
  rateLimitMax: "速率限制最大值",
  rateLimitWindow: "速率限制窗口",
  rateLimitPer: "速率限制周期",
  // 健康检查
  healthCheck: "健康检查",
  healthCheckEnabled: "健康检查启用",
  healthCheckInterval: "健康检查间隔",
  healthCheckTimeout: "健康检查超时",
  healthCheckPath: "健康检查路径",
  // 指标和遥测
  metricsEnabled: "指标启用",
  metricsPath: "指标路径",
  metricsPort: "指标端口",
  tracingEnabled: "追踪启用",
  tracingEndpoint: "追踪端点",
  // 安全相关
  sslEnabled: "SSL 启用",
  sslCert: "SSL 证书",
  sslKey: "SSL 密钥",
  sslCa: "SSL CA",
  tlsEnabled: "TLS 启用",
  tlsVersion: "TLS 版本",
  corsEnabled: "CORS 启用",
  corsOrigins: "CORS 来源",
  corsMethods: "CORS 方法",
  corsHeaders: "CORS 请求头",
  // 压缩相关
  compressionEnabled: "压缩启用",
  compressionLevel: "压缩级别",
  compressionThreshold: "压缩阈值",
  // 编码相关
  encodingEnabled: "编码启用",
  encodingType: "编码类型",
  charset: "字符集",
  // 验证相关
  validationEnabled: "验证启用",
  validationStrict: "严格验证",
  validationSchema: "验证架构",
  // 转换相关
  transformEnabled: "转换启用",
  transformInput: "转换输入",
  transformOutput: "转换输出",
  // 过滤相关
  filterEnabled: "过滤启用",
  filterInclude: "过滤包含",
  filterExclude: "过滤排除",
  // 排序相关
  sortEnabled: "排序启用",
  sortBy: "排序字段",
  sortOrder: "排序顺序",
  sortDirection: "排序方向",
  // 分页相关
  paginationEnabled: "分页启用",
  pageSize: "页面大小",
  pageNumber: "页码",
  pageOffset: "页面偏移",
  pageLimit: "页面限制",
  // 搜索相关
  searchQuery: "搜索查询",
  searchFields: "搜索字段",
  searchOperator: "搜索运算符",
  // 导出导入
  exportEnabled: "导出启用",
  exportFormat: "导出格式",
  exportPath: "导出路径",
  importEnabled: "导入启用",
  importFormat: "导入格式",
  importPath: "导入路径",
  // 备份恢复
  backupEnabled: "备份启用",
  backupPath: "备份路径",
  backupInterval: "备份间隔",
  restoreEnabled: "恢复启用",
  restorePath: "恢复路径",
  // 同步相关
  syncEnabled: "同步启用",
  syncInterval: "同步间隔",
  syncMode: "同步模式",
  // 通知相关
  notificationEnabled: "通知启用",
  notificationType: "通知类型",
  notificationChannel: "通知频道",
  // 调试相关
  debugEnabled: "调试启用",
  debugLevel: "调试级别",
  debugMode: "调试模式",
  verboseEnabled: "详细模式启用",
  // 实验性功能
  experimentalEnabled: "实验性功能启用",
  preview: "预览版",
  // 其他常用
  defaultValue: "默认值",
  fallbackValue: "回退值",
  overrideValue: "覆盖值",
  customValue: "自定义值",
  // 状态相关
  isEnabled: "是否启用",
  isActive: "是否活动",
  isRunning: "是否运行",
  isConnected: "是否连接",
  isConfigured: "是否配置",
  isReady: "是否就绪",
  isPaused: "是否暂停",
  isStopped: "是否停止",
  isError: "是否错误",
  // 时间戳
  createdAt: "创建时间",
  updatedAt: "更新时间",
  deletedAt: "删除时间",
  startedAt: "开始时间",
  endedAt: "结束时间",
  expiresAt: "过期时间",
  lastSeenAt: "最后在线时间",
  lastActiveAt: "最后活动时间",
  lastModifiedAt: "最后修改时间",
  // 计数器
  totalCount: "总数",
  successCount: "成功数",
  failureCount: "失败数",
  errorCount: "错误数",
  retryCount: "重试数",
  skipCount: "跳过数",
  // 持续时间
  durationMs: "持续时间毫秒",
  durationSeconds: "持续时间秒",
  durationMinutes: "持续时间分钟",
  durationHours: "持续时间小时",
  // 大小
  sizeBytes: "大小字节",
  sizeKb: "大小 KB",
  sizeMb: "大小 MB",
  sizeGb: "大小 GB",
  // Deepgram 和语音相关
  deepgram: "Deepgram",
  detectLanguage: "检测语言",
  punctuate: "标点符号",
  smartFormat: "智能格式",
  // 提供商和模型相关
  providerOptions: "提供商选项",
  providerFilter: "提供商过滤",
  bedrockDiscovery: "Bedrock 发现",
  defaultContextWindow: "默认上下文窗口",
  defaultMaxTokens: "默认最大令牌数",
  refreshInterval: "刷新间隔",
  // 附件和上下文
  maxAttachments: "最大附件数",
  crossContext: "跨上下文",
  // 沙箱和子代理
  sandbox: "沙箱",
  subagents: "子代理",
  // 心跳和重试
  heartbeatSeconds: "心跳秒数",
  initialMs: "初始毫秒",
  maxAttempts: "最大尝试次数",
  // 群聊和消息
  groupChat: "群聊",
  inbound: "入站",
  messagePrefix: "消息前缀",
  responsePrefix: "响应前缀",
  // 频道相关
  byChannel: "按频道",
  debounceMsByChannel: "按频道防抖毫秒",
  removeAckAfterReply: "回复后移除确认",
  // 更多消息相关
  replyTo: "回复给",
  forwardTo: "转发给",
  copyTo: "抄送给",
  bcc: "密送",
  // 更多时间相关
  delayMs: "延迟毫秒",
  waitMs: "等待毫秒",
  pollMs: "轮询毫秒",
  cooldownMs: "冷却毫秒",
  throttleMs: "节流毫秒",
  // 更多限制
  minLength: "最小长度",
  minSize: "最小大小",
  minCount: "最小数量",
  minValue: "最小值",
  maxValue: "最大值",
  // 更多开关
  skipEmpty: "跳过空值",
  skipNull: "跳过空",
  skipUndefined: "跳过未定义",
  trimWhitespace: "去除空白",
  toLowerCase: "转小写",
  toUpperCase: "转大写",
  // 更多状态
  cancelled: "已取消",
  skipped: "已跳过",
  // 更多动作
  create: "创建",
  read: "读取",
  get: "获取",
  set: "设置",
  add: "添加",
  // 更多配置
  inherit: "继承",
  // 更多网络
  hostname: "主机名",
  fragment: "片段",
  // 更多认证
  bearer: "Bearer",
  basic: "Basic",
  digest: "Digest",
  oauth: "OAuth",
  oauth2: "OAuth2",
  jwt: "JWT",
  saml: "SAML",
  ldap: "LDAP",
  // 更多加密
  salt: "盐值",
  iv: "初始向量",
  // 更多编码
  base64: "Base64",
  hex: "十六进制",
  utf8: "UTF-8",
  ascii: "ASCII",
  binary: "二进制",
  json: "JSON",
  xml: "XML",
  yaml: "YAML",
  csv: "CSV",
  // 更多压缩
  gzip: "Gzip",
  deflate: "Deflate",
  brotli: "Brotli",
  zstd: "Zstd",
  lz4: "LZ4",
  snappy: "Snappy",
  // 响应和传输
  transport: "传输",
  // 默认和执行
  exec: "执行",
  cooldowns: "冷却时间",
  strategy: "策略",
  // 策略值
  parallel: "并行",
  sequential: "顺序",
  // 实时和变量
  liveReload: "实时重载",
  vars: "变量",
  preserveFilenames: "保留文件名",
  // 代理间通信
  elevated: "提升权限",
  // 超时
  timeoutSec: "超时秒",
  // 规则和视频
  rules: "规则",
  video: "视频",
  // 模式值
  minimal: "最小",
  coding: "编程",
  messaging: "消息",
  full: "完整",
  // 更多常用字段
  requests: "请求",
  // 更多模式
  auto: "自动",
  manual: "手动",
  smart: "智能",
  simple: "简单",
  // 更多状态
  ready: "就绪",
  waiting: "等待中",
  stopped: "已停止",
  // 更多动作
  send: "发送",
  receive: "接收",
  async: "异步",
  batch: "批量",
  // 更多配置
  preferences: "偏好",
  flags: "标志",
  // 更多网络
  ws: "WebSocket",
  wss: "WebSocket 安全",
  // 更多存储
  disk: "磁盘",
  blob: "Blob",
  // 更多时间
  now: "现在",
  today: "今天",
  yesterday: "昨天",
  tomorrow: "明天",
  always: "始终",
  never: "从不",
  once: "一次",
  daily: "每天",
  weekly: "每周",
  monthly: "每月",
  yearly: "每年",
  // 更多布尔
  yes: "是",
  no: "否",
  true: "真",
  false: "假",
  on: "开",
  off: "关",
  // 更多方向
  up: "上",
  down: "下",
  left: "左",
  right: "右",
  top: "顶部",
  bottom: "底部",
  center: "中心",
  // 更多大小
  small: "小",
  medium: "中",
  large: "大",
  tiny: "微小",
  huge: "巨大",
  // 更多优先级
  low: "低",
  normal: "正常",
  high: "高",
  critical: "关键",
  urgent: "紧急",
  // 更多类型
  number: "数字",
  boolean: "布尔",
  array: "数组",
  object: "对象",
  string: "字符串",
  integer: "整数",
  float: "浮点数",
  datetime: "日期时间",
  // 更多格式
  raw: "原始",
  formatted: "格式化",
  pretty: "美化",
  compact: "紧凑",
  minified: "压缩",
  // 更多范围
  all: "全部",
  none: "无",
  some: "部分",
  any: "任意",
  every: "每个",
  // 更多操作
  copy: "复制",
  paste: "粘贴",
  cut: "剪切",
  undo: "撤销",
  redo: "重做",
  save: "保存",
  // 更多视图
  toggle: "切换",
  // 更多选择
  select: "选择",
  deselect: "取消选择",
  selectAll: "全选",
  deselectAll: "取消全选",
  // 更多过滤
  include: "包含",
  exclude: "排除",
  only: "仅",
  except: "除了",
  // 默认和分块
  defaults: "默认值",
  chunking: "分块",
  // 模型和缓存
  modelCacheDir: "模型缓存目录",
  wait: "等待",
  store: "存储",
  // 容器相关
  memorySwap: "内存交换",
  extraHosts: "额外主机",
  pidsLimit: "进程数限制",
  readOnlyRoot: "只读根目录",
  setupCommand: "设置命令",
  // 会话和工具
  sessionToolsVisibility: "会话工具可见性",
  workspaceAccess: "工作区访问",
  workspaceRoot: "工作区根目录",
  skipBootstrap: "跳过引导",
  // 过滤器
  agentFilter: "代理过滤器",
  sessionFilter: "会话过滤器",
  targets: "目标",
  // 代理间通信
  agentToAgent: "代理间通信",
  backgroundMs: "后台毫秒",
  cleanupMs: "清理毫秒",
  // 链接和标记
  links: "链接",
  marker: "标记",
  // 转录
  transcription: "转录",
  // 历史和提及
  historyLimit: "历史限制",
  mentionPatterns: "提及模式",
  // 空闲和重置
  idleMinutes: "空闲分钟",
  resetByChannel: "按频道重置",
  resetByType: "按类型重置",
  resetTriggers: "重置触发器",
  // 发送策略
  sendPolicy: "发送策略",
  maxConcurrentRuns: "最大并发运行数",
  // 安全和内容
  allowUnsafeExternalContent: "允许不安全外部内容",
  hookUrl: "钩子 URL",
  includeBody: "包含正文",
  // 订阅
  subscription: "订阅",
  internal: "内部",
  assistant: "助手",
  // 更多容器设置
  privileged: "特权模式",
  networkMode: "网络模式",
  capAdd: "添加能力",
  capDrop: "删除能力",
  securityOpt: "安全选项",
  tmpfs: "临时文件系统",
  volumes: "卷",
  // 更多会话设置
  sessionName: "会话名称",
  sessionType: "会话类型",
  sessionState: "会话状态",
  // 更多工作区设置
  workspacePath: "工作区路径",
  workspaceId: "工作区 ID",
  workspaceName: "工作区名称",
  // 更多过滤设置
  filterBy: "过滤条件",
  filterValue: "过滤值",
  filterType: "过滤类型",
  // 更多重置设置
  resetOnError: "错误时重置",
  resetOnTimeout: "超时时重置",
  resetOnDisconnect: "断开时重置",
  // 更多策略设置
  policyName: "策略名称",
  policyType: "策略类型",
  policyValue: "策略值",
  // 更多钩子设置
  hookName: "钩子名称",
  hookType: "钩子类型",
  hookEnabled: "钩子启用",
  // 更多订阅设置
  subscriptionId: "订阅 ID",
  subscriptionName: "订阅名称",
  subscriptionType: "订阅类型",
  subscriptionStatus: "订阅状态",
};

export function humanize(raw: string) {
  // 首先检查是否有直接翻译
  if (FIELD_TRANSLATIONS[raw]) {
    return FIELD_TRANSLATIONS[raw];
  }

  // 检查小写版本
  const lowerRaw = raw.toLowerCase();
  if (FIELD_TRANSLATIONS[lowerRaw]) {
    return FIELD_TRANSLATIONS[lowerRaw];
  }

  // 如果没有翻译，返回原始的英文格式化结果
  return raw
    .replace(/_/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/\s+/g, " ")
    .replace(/^./, (m) => m.toUpperCase());
}
